version: '3.8'

services:
  node:
    image: node:18
    environment:
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
      DEBUG_PORT: ${DEBUG_PORT}
      DEBUG_HOST: ${DEBUG_HOST}
      APP_NAME: ${APP_NAME}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      SWAGGER_TITLE: ${SWAGGER_TITLE}
      SWAGGER_PATH: ${SWAGGER_PATH}
      SWAGGER_DESCRIPTION: ${SWAGGER_DESCRIPTION}
      SWAGGER_VERSION: ${SWAGGER_VERSION}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      PROMETHEUS_NAMESPACE: ${PROMETHEUS_NAMESPACE}
      VISA_JWT_KEY_VALUE: ${VISA_JWT_KEY_VALUE}
      VISA_JWT_KEY_PASSPHRASE: ${VISA_JWT_KEY_PASSPHRASE}
      VISA_JWT_KEY_FORMAT: ${VISA_JWT_KEY_FORMAT}
      VISA_JWT_ALGORITHM: ${VISA_JWT_ALGORITHM}
      VISA_JWT_ENCRYPTION: ${VISA_JWT_ENCRYPTION}
      VISA_JWT_COMPRESSION: ${VISA_JWT_COMPRESSION}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "${HTTP_PORT}:3000"
      - "${DEBUG_PORT}:9229"
    entrypoint: npm run start:debug
